# This workflow _produces_ caches which are used to speed up pull request builds.
# Originally from https://github.com/libp2p/rust-libp2p/blob/master/.github/workflows/cache-factory.yml

name: Cache Factory

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make_cache:
    name: 'Make Cache'
    runs-on: ubuntu-latest
    env:
        CARGO_BUILD_TARGET: x86_64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust stable
        run: |
          rustup toolchain install stable

      - name: Generate Prisma client
        env:
          CARGO_BUILD_TARGET: x86_64-unknown-linux-gnu
        uses: ./.github/actions/generate-prisma-client

      - name: Install Rust stable
        run: |
          rustup target add $CARGO_BUILD_TARGET
          rustup toolchain install stable-$CARGO_BUILD_TARGET

      - name: Install musl-tools
        run: sudo apt-get install musl-tools

      - name: Compile workspace with stable Rust
        run: cargo test --workspace --all-features --no-run --target $CARGO_BUILD_TARGET
